export type View = 'inicio' | 'galeria' | 'biografia' | 'livro' | 'contacto' | 'links' | 'admin';

export interface ImageProps {
  id: string;
  url: string;
  thumbnailUrl?: string;
  alt?: string;
  title?: string;
  subtitle?: string;
  description?: string;
  category?: string;
  orientation?: 'landscape' | 'portrait' | 'square';
  order?: number;
  featured?: boolean;
  cameraSettings?: string;
  cameraModel?: string;
  lens?: string;
  iso?: string;
  aperture?: string;
  shutterSpeed?: string;
  createdAt?: any;
  storagePath?: string;
}

export interface SiteSettings {
  // Global Page Titles & Subtitles (Applies to all main sections)
  pageTitleFont?: string;
  pageTitleFontSize?: string;
  pageTitleColor?: string;
  pageTitleLetterSpacing?: string;
  pageTitleStyle?: string;
  pageTitleSubtitleSpacing?: number;

  pageSubtitleFont?: string;
  pageSubtitleFontSize?: string;
  pageSubtitleColor?: string;
  pageSubtitleLetterSpacing?: string;
  pageSubtitleStyle?: string;

  siteName: string;
  siteSubtitle?: string;
  siteNameFont: string;
  siteNameFontSize: number;
  siteNameColor: string;
  sidebarTitleTopMargin: number;
  sidebarTitleBottomMargin: number;
  sidebarTitleLeftMargin: number;
  sidebarTitleRightMargin: number;
  sidebarFooterBottomMargin: number;
  mainTitleTopMargin: number;
  mainTitleBottomMargin: number;
  showPageHeaderTitle?: boolean;
  showPageHeaderLines?: boolean;
  separateFooterDiv?: boolean;
  mobileTitle: string;
  welcomeMessage: string;
  messageSpacing: number;
  messageFont: string;
  messageFontSize: number;
  messageAlignment: string;
  messageColor: string;
  contactEmail: string;
  profilePhoto: string;
  biography: string;
  publishedWorks?: string;
  exhibitions?: string;

  // Biography Page Typography & Titles
  gallerySectionTitle?: string;
  gallerySectionSubtitle?: string;
  biographySectionTitle?: string;
  biographySectionSubtitle?: string;
  biographyTitleFont?: string;
  biographyTitleFontSize?: string;
  biographyTitleColor?: string;
  biographyTitleStyle?: string;
  biographyTitleLetterSpacing?: string;
  biographySubtitleFont?: string;
  biographySubtitleFontSize?: string;
  biographySubtitleColor?: string;
  biographySubtitleStyle?: string;
  biographySubtitleLetterSpacing?: string;
  biographyFont?: string;
  biographyFontSize?: string;
  biographyColor?: string;
  biographyStyle?: string;
  biographyLetterSpacing?: string;

  biographyTitleSubtitleSpacing?: number;
  // Published Works Titles & Typography
  publishedWorksSectionTitle?: string;
  publishedWorksFont?: string;
  publishedWorksFontSize?: string;
  publishedWorksColor?: string;
  publishedWorksStyle?: string;
  publishedWorksLetterSpacing?: string;

  // Exhibitions Titles & Typography
  exhibitionsSectionTitle?: string;
  exhibitionsFont?: string;
  exhibitionsFontSize?: string;
  exhibitionsColor?: string;
  exhibitionsStyle?: string;
  exhibitionsLetterSpacing?: string;

  // Contact Page Titles & Typography
  contactSectionTitle?: string;
  contactSectionSubtitle?: string;
  contactTitleFont?: string;
  contactTitleFontSize?: string;
  contactTitleColor?: string;
  contactTitleStyle?: string;
  contactTitleLetterSpacing?: string;
  contactSubtitleFont?: string;
  contactSubtitleFontSize?: string;
  contactSubtitleColor?: string;
  contactSubtitleStyle?: string;
  contactSubtitleLetterSpacing?: string;
  contactFormLabelFont?: string;
  contactFormLabelSize?: string;
  contactFormLabelColor?: string;
  contactFormLabelLetterSpacing?: string;
  contactTitleSubtitleSpacing?: number;

  // Guestbook Page Titles & Typography
  guestbookSectionTitle?: string;
  guestbookSectionSubtitle?: string;
  guestbookSubtitleMode?: 'subtitle_only' | 'count_only' | 'both';
  guestbookTitleFont?: string;
  guestbookTitleFontSize?: string;
  guestbookTitleColor?: string;
  guestbookTitleStyle?: string;
  guestbookTitleLetterSpacing?: string;
  guestbookSubtitleFont?: string;
  guestbookSubtitleFontSize?: string;
  guestbookSubtitleColor?: string;
  guestbookSubtitleStyle?: string;
  guestbookSubtitleLetterSpacing?: string;
  guestbookTitleSubtitleSpacing?: number;

  // Links Page Titles & Typography
  linksSectionTitle?: string;
  linksSectionSubtitle?: string;
  linksTitleFont?: string;
  linksTitleFontSize?: string;
  linksTitleColor?: string;
  linksTitleStyle?: string;
  linksTitleLetterSpacing?: string;
  linksSubtitleFont?: string;
  linksSubtitleFontSize?: string;
  linksSubtitleColor?: string;
  linksSubtitleStyle?: string;
  linksSubtitleLetterSpacing?: string;
  linksTitleSubtitleSpacing?: number;
  instagram: string;
  facebook: string;
  twitter: string;
  globalFont: string;
  globalColor: string;
  menuLines: string;
  menuLinesColor: string;
  menuFont: string;
  menuColor: string;
  sidebarButtonSpacing: number;
  footerBottomSpacing: number;
  slideshowPhotoPadding: number;
  slideshowInterval: number;
  slideshowFit: string;
  slideshowTopMargin: number;
  showSlideshowGalleryButton?: boolean;
  slideshowGalleryButtonPosition?: 'left' | 'center' | 'right';
  categories: string[];
  showExifData: boolean;
  enableKeyboardShortcuts: boolean;
  enableZenMode: boolean;
  enableWatermark: boolean;
  watermarkText: string;
  watermarkPosition: string;
  enableGallerySearch: boolean;
  enableFavorites: boolean;
  enablePhotoComparison: boolean;
  footerText: string;

  // Text Styles & Letter Spacing
  globalLetterSpacing?: string;
  siteNameLetterSpacing?: string;
  messageLetterSpacing?: string;
  menuLetterSpacing?: string;
  siteNameTextStyle?: string;
  messageTextStyle?: string;
  menuTextStyle?: string;
  showLightboxCategory?: boolean;
  lightboxCategoryPosition?: string;
  lightboxCategoryPlacement?: 'inside' | 'outside';
  lightboxCategoryPadding?: number;
  lightboxCategoryFont?: string;
  lightboxCategorySize?: string;
  lightboxCategoryStyle?: string;
  lightboxCategoryColor?: string;
  lightboxCategoryLetterSpacing?: string;
  enableLightboxCategoryBg?: boolean;
  lightboxCategoryBgColor?: string;
  lightboxTitleStyle?: string;
  lightboxTitleLetterSpacing?: string;
  lightboxSubtitleStyle?: string;
  lightboxSubtitleLetterSpacing?: string;
  slideshowTitleStyle?: string;
  slideshowTitleLetterSpacing?: string;
  slideshowSubtitleStyle?: string;
  slideshowSubtitleLetterSpacing?: string;
  slideshowControlsLetterSpacing?: string;
  rightClickTitleStyle?: string;
  rightClickTitleLetterSpacing?: string;
  rightClickSubtitleStyle?: string;
  rightClickSubtitleLetterSpacing?: string;
  enableLightboxTextBg?: boolean;
  lightboxTextBgColor?: string;
  lightboxCaptionPlacement?: 'inside' | 'outside';
  lightboxCaptionPadding?: number;
  enableSlideshowTextBg?: boolean;
  slideshowTextBgColor?: string;
  slideshowCaptionPlacement?: 'inside' | 'outside';
  slideshowCaptionPadding?: number;
  
  // Missing properties from Settings Panel Tabs
  importQuality?: string;
  lightboxQuality?: string;
  adminThumbSizePx?: number;
  thumbnailSize?: string;
  galleryGridCols?: string;
  compressQuality?: number;
  enableSharpen?: boolean;
  sharpenAmount?: number;
  galleryTheme?: string;
  showCaptions?: string;
  captionPosition?: string;
  lightboxEffect?: string;
  lightboxArrowsDesktopLandscape?: string;
  lightboxArrowsDesktopPortrait?: string;
  lightboxArrowsMobileLandscape?: string;
  lightboxArrowsMobilePortrait?: string;
  defaultZoomLevel?: number;
  lightboxBgColor?: string;
  protectPhotos?: boolean;
  enableRightClickMessage?: boolean;
  rightClickTitle?: string;
  rightClickSubtitle?: string;
  rightClickFont?: string;
  rightClickSize?: string;
  rightClickColor?: string;
  rightClickBgColor?: string;
  zenModeButtonColor?: string;
  zenModeButtonBgColor?: string;
  showWatermarkInSlideshow?: boolean;
  slideshowWatermarkPosition?: string;
  enablePhotoDownload?: boolean;
  enableMonochromeToggle?: boolean;
  enablePhotoLikes?: boolean;
  lightboxTitleFont?: string;
  lightboxSubtitleFont?: string;
  lightboxTitleSize?: string;
  lightboxSubtitleSize?: string;
  lightboxTextPosition?: string;
  lightboxTextColor?: string;
  slideshowEffect?: string;
  slideshowZoom?: number;
  slideshowBgColor?: string;
  slideshowTitleFont?: string;
  slideshowSubtitleFont?: string;
  slideshowTitleSize?: string;
  slideshowSubtitleSize?: string;
  slideshowControlsPosition?: string;
  slideshowControlsAlign?: string;
  slideshowControlsFont?: string;
  slideshowControlsSize?: string;
  slideshowControlsColor?: string;
  showSlideshowCaptions?: boolean;
  slideshowTextPosition?: string;
  slideshowTextColor?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: string;
  googleAnalyticsId?: string;
  adminPassword?: string;
  reduceAnimations?: boolean;
  enableCookieConsent?: boolean;
  maintenanceMode?: boolean;
  customCss?: string;
}
